export { default as SplashScreen } from '@screens/login/SplashScreen'
export { default as HomeScreen } from '@screens/home/HomeScreen'
export { default as LoginScreen } from '@screens/login/LoginScreen'
export { default as DetailScreen } from '@screens/detail/DetailScreen'
export { default as ForgotPasswordScreen } from '@screens/login/ForgotPasswordScreen'
export { default as RegisterScreen } from '@screens/login/RegisterScreen'
export { default as FoodScreen } from '@screens/detail/FoodSection'
